### ISSUE TITLE
Add an option to use bestEffort and readOnly queries.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#104]
This is an important feature. The "best effort" and "read only" we eventually recommend users to do in certain scenarios. So it would be good to be in Ratel due to ease of use (of Ratel).

> dmai 4:01 PM
> HTTP supports read-only and best-effort with /query?ro=true and /query?be=true

**Comment by paulftw** [comment]
My understanding is bestEffort/readOnly is more important for production systems under high load as it allows to shave off some milliseconds off a query.
Since Ratel is used by humans in a manual mode I doubt they will be able to notice any difference, so there's probably not that much value in having it in Ratel. Will mark it as a low priority.

**Comment by MichelDiz** [comment]
This is done
