### ISSUE TITLE
[Missing] Console Alter tab not exists any more

### ISSUE THREAD

**Issue by vzool** [dgraph-io/ratel#143]
Hi, I'm walking through [dGraph tour](https://tour.dgraph.io/intro/3/#) and the tour said that I should run the command in the Alter console command, which is not exists in the final release. Where can I found it?

![Screenshot from 2019-11-21 16-44-11](https://user-images.githubusercontent.com/4952736/69343325-7c5b6b00-0c7e-11ea-8f6d-46da4bef78e5.png)

Thanks

**Comment by shekarm** [comment]
The Run button is on the top right corner.

**Comment by vzool** [comment]
No, old version contains: Query, Alter & Mutate. But, in latest version the Mutate option has been disappeared. :(

**Comment by shekarm** [comment]
The mutate option is right there. You mean the 'Alter' option has disappeared?

**Comment by shekarm** [comment]
Ok, I will assign this to one of our engineers.

**Comment by vzool** [comment]
Okey, here is the version information:
```
Built at 2019-11-15T14:24:47.307Z
Commit: 919e808
Commit Info: 919e808 Fri Nov 15 16:22:11 2019 +0200 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by shekarm** [comment]
Thank you. I have asked one of our engineers to take a look at. We should get back to you soon. 

—
Shekar Mantha



https://dgraph.io

--- original message ---
On November 22, 2019, 1:19 AM EST notifications@github.com wrote:


Okey, here is the version information:

Built at 2019-11-15T14:24:47.307Z
Commit: 919e808
Commit Info: 919e808 Fri Nov 15 16:22:11 2019 +0200 (HEAD -> master, origin/master, origin/HEAD)

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by paulftw** [comment]
@vzool Alter tab was deprecated when Schema tab was introduced.

You can get the same behavior as Alter if you go to Schema > Bulk Edit.

Typing or pasting alter commands there and clicking Apply actually uses /alter endpoint.

I will file a bug against Dgraph Tour repo to update the instructions.
Closing this one as working as expected.

cc @shekarm
