### ISSUE TITLE
When scrolling down on the predicates of a Type it scrolls back to the latest checked checkbox

### ISSUE THREAD

**Issue by ChStark** [dgraph-io/ratel#155]
When scrolling down on the predicates of a Type (Edit type modal) it scrolls up to the latest checked checkbox after scrolling down further

User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Comment by shekarm** [comment]
What exactly does this mean? 

--- original message ---
On Fri, Jan 3 at 06:41 PM, <notifications@github.com> Jorge Garza wrote:


When scrolling down on the predicates of a Type it scrolls up to the latest checked checkbox after scrolling down further

User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by paulftw** [comment]
This has stopped happening for me Chrome and Safari after the grid component upgrade and connection code refactoring.

Verified by creating a database with 30+ predicates and creating or editing a type. In either case scrolling behaved as expected.

Please let me know if you are still affected by this.

Closing the issue for now, will re-open if any new information is available
