### ISSUE TITLE
Running Drop All can make Ratel unresponsive

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#60]
If DropAll takes a while to run Ratel no longer responds to queries or mutations with no indication of work being done.

**Comment by paulftw** [comment]
Having difficulties reproducing this - tried injecting hooks that caused drop_all to take really long, fail, wait and fail, etc.
d3 ratel seems to perform ok - it's just a background XML RPC that hasn't completed.

@danielmai  Is this reproducible with your setup? can it be due to the fact dgraph is busy and unresponsive, which'd make Ratel seem slow?

**Comment by paulftw** [comment]
Seems like this was a one off issue
